### ISSUE TITLE
[feature request]: Support for Cloudflare Pages

### ISSUE THREAD

**Issue by vanstinator** [evanderkoogh/otel-cf-workers#96]
We're starting to use Cloudflare Pages at Plex for a new layer in our API. We're also heavy users of Datadog, and would like to be able to auto-instrument our Pages codebase so we have e2e traces across our backend stack.

I've been hacking on some support for this, and we have it working internally. Would you be interested in a taking a PR that adds support for CF Pages auto-instrumentation?

I have an in-progress hacked together branch on my fork https://github.com/evanderkoogh/otel-cf-workers/compare/main...vanstinator:otel-cf-workers:feat/cf-pages

The code ended up being almost identical to the fetch instrumentation. I think it will be relatively trivial to clean up my exploration work and land on a solution that extends the fetch functionality with a few additional lines of code and another function export.

If this sounds good I can probably schedule work to productionize the patch in the next month or two.

**Comment by jahands** [comment]
Hey @vanstinator! Your branch looks like a pretty good start to me. Definitely welcome to PRs to add Pages support!

**Comment by dustinsmith1024** [comment]
@vanstinator - does Datadog provide a public trace endpoint or do you run your own public agent to send the data to?

**Comment by vanstinator** [comment]
For the time being we're going to be running an agent. I'm not sure how we'll expose it yet, those discussions are still happening internally.

**Comment by jfsiii** [comment]
I'd love to see this! We're running Remix on Workers Sites for now, but we won't be able to for long. The latest Remix (using Vite vs esbuild) doesn't support Workers Sites any longer because [they're deprecated for full-stack apps](https://developers.cloudflare.com/workers/configuration/sites/)


<img width="834" alt="Screenshot 2024-04-13 at 4 04 55 PM" src="https://github.com/evanderkoogh/otel-cf-workers/assets/57655/14ec97ac-ca80-430a-8793-515cc8e74d00">

I'm working on the replacement now, and would be happy to help test this out

**Comment by jfsiii** [comment]
@vanstinator are you opposed to opening the PR now so this can be merged and allow others to debug/contribute?

As I [mentioned](https://github.com/evanderkoogh/otel-cf-workers/issues/96#issuecomment-2053746599) we'll soon need to use Pages for our Remix app and I'd love to have this (or be able to debug/fix any issues I find while testing)

**Comment by vanstinator** [comment]
Hey @jfsiii I think I can make that happen. I'll lightly clean up my branch today and get a PR open!

**Comment by vanstinator** [comment]
The PR is up!

**Comment by Pelps12** [comment]
Any progress on this issue?

**Comment by evanderkoogh** [comment]
Unfortunately not. I was forced to step back from maintaining this for the better part of a year and @jahands and co have done an amazing job at keeping the lights on, but didn't have a lot of time to work on adding new features.

I am back, so will spend some time over the next week or so to get my bearing and work on it again.

My first priority is to ship a 1.0 and get any breaking changes out of the way as much as I can. My next priority is to go through some of the PRs that implement new features and incorporate those too. That includes this one.

**Comment by vanstinator** [comment]
I left the job that was building this out, and I don't have any personal projects on CF-workers where I'd need this unfortunately.

**Comment by n3oney** [comment]
fwiw this seems to work for Next.js:


```ts
import { OTLPExporter } from "@microlabs/otel-cf-workers";
import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-node";
import { registerOTel } from "@vercel/otel";

export function register() {
  registerOTel({
    serviceName: "nextjs-app",
    spanProcessors: [
      // @ts-expect-error  for some reason the type doesn't match but it actually works
      new SimpleSpanProcessor(
        new OTLPExporter({
          url: "yourURL",
          headers: {
            // req headers
          },
        }),
      ),
    ],
  });
}
```

**Comment by pipech** [comment]
> fwiw this seems to work for Next.js:
> 
> // instrumentation.ts
> 
> import { OTLPExporter } from "@microlabs/otel-cf-workers";
> import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-node";
> import { registerOTel } from "@vercel/otel";
> 
> export function register() {
>   registerOTel({
>     serviceName: "nextjs-app",
>     spanProcessors: [
>       // @ts-expect-error  for some reason the type doesn't match but it actually works
>       new SimpleSpanProcessor(
>         new OTLPExporter({
>           url: "yourURL",
>           headers: {
>             // req headers
>           },
>         }),
>       ),
>     ],
>   });
> }

This doesn't seems to work, got an error when I tried to build within cloudflare worker.

```
2025-09-08T07:37:17.475Z	https://nextjs.org/telemetry
2025-09-08T07:37:17.475Z	
2025-09-08T07:37:21.033Z	   ▲ Next.js 15.3.5
2025-09-08T07:37:21.033Z	
2025-09-08T07:37:21.070Z	   Creating an optimized production build ...
2025-09-08T07:38:10.386Z	Failed to compile.
2025-09-08T07:38:10.389Z	
2025-09-08T07:38:10.393Z	cloudflare:workers
2025-09-08T07:38:10.393Z	Module build failed: UnhandledSchemeError: Reading from "cloudflare:workers" is not handled by plugins (Unhandled scheme).
2025-09-08T07:38:10.394Z	Webpack supports "data:" and "file:" URIs by default.
2025-09-08T07:38:10.394Z	You may need an additional plugin to handle "cloudflare:" URIs.
2025-09-08T07:38:10.394Z	    at /opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:29:408376
2025-09-08T07:38:10.394Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:14:9224), <anonymous>:6:1)
2025-09-08T07:38:10.394Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:14:6378)
2025-09-08T07:38:10.394Z	    at Object.processResource (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:29:408301)
2025-09-08T07:38:10.395Z	    at processResource (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
2025-09-08T07:38:10.395Z	    at iteratePitchingLoaders (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
2025-09-08T07:38:10.395Z	    at runLoaders (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
2025-09-08T07:38:10.395Z	    at NormalModule._doBuild (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:29:408163)
2025-09-08T07:38:10.395Z	    at NormalModule.build (/opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:29:410176)
2025-09-08T07:38:10.395Z	    at /opt/buildhome/repo/node_modules/.pnpm/next@15.3.5_@babel+core@7.24.9_@opentelemetry+api@1.9.0_@playwright+test@1.45.2_babel-p_96f88ca74759ba09498e497a949e0012/node_modules/next/dist/compiled/webpack/bundle5.js:29:82494
```

Then I found this issues.

> There is no way we can support importing cloudflare:* packages within the Node runtime used when executing next dev.

https://github.com/opennextjs/opennextjs-cloudflare/issues/578#issuecomment-2801942715

Even after taking only `OTLPExporter` from https://github.com/evanderkoogh/otel-cf-workers/blob/effeb549f0a4ed1c55ea0c4f0d8e8e37e5494fb3/src/exporter.ts#L21 to skip `Module build failed: UnhandledSchemeError: Reading from "cloudflare:workers" is not handled by plugins (Unhandled scheme).` error, then I would encounter with another bugs.

**Comment by n3oney** [comment]
@pipech opennextjs is cloudflare workers not pages, so this is a separate issue. the code I provided is for next-on-pages

**Comment by pipech** [comment]
Noted, thank you for the reply.

It seems like the same code snippet so I thought it would also work with Opennextjs.
